spring.application.name=checkmate
spring.profiles.active=${PROFILE}

# Database
spring.data.mongodb.uri=${DATABASE_URI}

# Redis
spring.data.redis.host=${REDIS_URI}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Cors
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Slack
slack.webhook.alert.url=${SLACK_WEBHOOK_URI}

# AI External Server
ai.external.server.url=${AI_EXTERNAL_SERVER_URI}

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH}
spring.mail.properties.mail.smtp.timeout=${MAIL_TIMEOUT}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS}

# Jwt
spring.jwt.secret=${JWT_SECRET}
spring.jwt.access-token-expiration=${JWT_EXPIRATION}

# Feign
spring.cloud.openfeign.client.config.default.connect-timeout= 5000
spring.cloud.openfeign.client.config.default.read-timeout= 500000

# PortOne
portone.secret.secret=${PORTONE_SECRET}
portone.secret.store.id=${PORTONE_STORE_ID}

# Object Storage
ncloud.endpoint=${NCLOUD_ENDPOINT}
ncloud.user=${NCLOUD_USER}
ncloud.password=${NCLOUD_PASSWORD}
ncloud.region=${NCLOUD_REGION}
