name: Build and Push to OCI
on:
  push:
    branches:
      - main
      - "CM-18"

env:
  IMAGE_NAME: yny.ocir.io/ax1nm9kw34v6/checkmate

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to OCI Container Registry
        uses: docker/login-action@v3
        with:
          registry: yny.ocir.io
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build \
            --platform linux/arm64 \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} \
            . 

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}