name: Test, Build and Deploy to OCI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - 'main'

env:
  IMAGE_NAME: ${{ secrets.OCI_IMAGE_NAME }}

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: [self-hosted, checkmate]
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew clean test jacocoTestReport

      - name: Upload JUnit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: build/reports/tests/test

      - name: Upload JaCoCo Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/jacocoHtml

  build-and-deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, checkmate]
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4

      - name: Log in to OCI Container Registry
        run: |
          echo "${{ secrets.OCI_REGISTRY_PASSWORD }}" | docker login yny.ocir.io -u "${{ secrets.OCI_REGISTRY_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build \
            --platform linux/arm64 \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} \
            .

          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Checkout Manifest Repository
        uses: actions/checkout@v4
        with:
          repository: starmix-ajou/checkmate-manifest
          token: ${{ secrets.PAT_TOKEN }}
          path: manifests

      - name: Update Image Tag in Deployment YAML
        run: |
          sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:${{ github.sha }}|" manifests/apps/backend/deployment.yaml

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Generate Argo CD Application with Webhook Secret
        run: |
          export WEBHOOK_SECRET="${{ secrets.WEBHOOK_SECRET }}"
          envsubst < manifests/apps/backend/application.yaml > manifests/apps/backend/application.yaml.tmp
          mv manifests/apps/backend/application.yaml.tmp manifests/apps/backend/application.yaml

      - name: Commit and Push Changes to Manifest Repo
        run: |
          cd manifests
          git config user.name "yeonnnnjs"
          git config user.email "sungyeon52@gmail.com"
          git commit -am "Update image tag from checkmate-backend"
          git push origin main